// src/main/react-app/src/components/Login.js
import { useContext, useState } from 'react';
import { useHistory } from 'react-router';
import { UserContext } from './UserContext';
import { myAxios, setAxiosToken } from '../util/axios-util';
import { Button, TextField, Container } from '@material-ui/core';
import { Alert } from '@material-ui/lab';
import { styled } from '@material-ui/core/styles';

export default function Login() {

  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [password2, setPassword2] = useState("");
  const [alert, setAlert] = useState(null);

  const { setUser } = useContext(UserContext);
  const history = useHistory();

  function loginOrRegister() {
      let action;
      if (!password2) {
        action = "login";
      } else if (password === password2) {
        action = "register";
      } else {
        setAlert({severity:"error", text:"Passwords don't match"});
        return;
      }
      setAlert({severity:"info", text:"Trying " + action});
      const loginData = {username, password, password2};
      myAxios
        .post("security/" + action, loginData)
        .then(resp => handleCredentials(resp.data))
        .catch(e => setAlert({severity:"error", text:e}));
    }

  function handleCredentials(creds) {
    console.log("Received credentials", creds);
    setAlert(null);
    setAxiosToken(creds.token);
    setUser(creds);
    history.replace("/");
  }

  const LoginButton = styled(Button)({
    margin: '20px 0',
  });

  return (
    <Container maxWidth="sm">
      <h1>Linklist</h1>
      <div>
        <TextField label="username" fullWidth
          value={username} onChange={e => setUsername(e.target.value)} />
      </div>
      <div>
        <TextField label="password" type="password" fullWidth 
          value={password} onChange={e => setPassword(e.target.value)} />
      </div>
      <div>
        <TextField label="repeat password to register" type="password" fullWidth
          value={password2} onChange={e => setPassword2(e.target.value)} />
      </div>
      <div>
        <LoginButton variant="contained" color="primary"
          onClick={loginOrRegister}>Login</LoginButton>
      </div>
      <div>
        { alert ? <Alert severity={alert.severity}>{alert.text}</Alert> : "" }
      </div>
    </Container>
  );
}

// src/main/vue-app/src/components/Login.vue
<template>
  <div>
    <v-app-bar app dark>
      <v-toolbar-title>Login</v-toolbar-title>
      <v-progress-circular v-if="loading" class="load-progress"
          :width="3" :size="20" indeterminate color="primary" />
      <v-spacer></v-spacer>
      <v-btn icon @click="loginOrRegister()"><v-icon>mdi-login</v-icon></v-btn>
    </v-app-bar>
    <v-main>
      <v-card flat tile dark>
        <v-container>
          <v-alert v-model="error.visible" color="red" dismissible type="error">{{ error.message }}</v-alert>
          <v-alert v-model="info.visible" dismissible type="info">{{ info.message }}</v-alert>
        </v-container>
        <v-container>
          <v-text-field v-model="loginData.username" label="username" auto-grow rows="1" />
          <v-text-field v-model="loginData.password" type="password" label="password" auto-grow rows="1" />
          <v-text-field v-model="loginData.password2" type="password" label="repeat password to register" auto-grow rows="1" />
        </v-container>
      </v-card>
    </v-main>
  </div>
</template>

<script>
import axios from "axios";
import constants from "@/constants";
import Util from '@/util';

export default {
  name: 'Login',
  data: () => ({
    loginData: { username: "", password: "", password2: "" },
    error: { visible: false },
    info: { visible: false },
    loading: false
  }),
  methods: {
    loginOrRegister() {
      let action;
      if (!this.loginData.password2) {
        action = "login";
      } else if (this.loginData.password === this.loginData.password2) {
        action = "register";
      } else {
        this.error = { message: "Passwords don't match", visible: true };
        return;
      }
      let url = constants.apiUrl + "/security/" + action;
      console.log("Login with url: ", url);

      Util.loadWithAxios("login", this, () =>
          axios
              .post(url, this.loginData)
              .then(resp => this.handleCredentials(resp.data))
      );
    },
    handleCredentials(credentials) {
      // const tokenPart = credentials.token ? credentials.token.substr(0, 10) + "..." : "(none)";
      // this.info = { message: "Received user " + credentials.username + " and token " + tokenPart, visible: true }
      this.$emit("login", credentials);
    },
    handleError(e) {
      this.error = Util.messageObjectFromApiError(e);
    }
  }
};
</script>

<style scoped lang="scss">
.load-progress {
  margin-left: 10px;
}
</style>
